mode=manual-update
current_mc_version=26.1.2
target_mc_version=26.2
current_mod_version=1.7-26.1.2
target_mod_version=1.7-26.2
target_mappings_channel=none
target_loader_version=0.19.3
target_fabric_version=0.152.2+26.2
target_yarn_mappings=
